### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by elpaxel** [DoctorMcKay/node-steam-session#10]
First of all thanks you for this robust library.

So when I'm authenticating with "startWithCredentials" and then send wrong auth code with "submitSteamGuardCode" I'm getting expected "TwoFactorCodeMismatch". Then if I'm not doing anything, ~1 minute passes and Steam sends "ClientLogOnResponse", library calls [disconnect](https://github.com/DoctorMcKay/node-steam-session/blob/5f07f735b8e219c2d976539ceb45d772e946dfe8/src/transports/WebSocketCMTransport.ts#L238) and my program exits silently.

It is all good because as expected I'm catching "TwoFactorCodeMismatch" and then send new auth code. But it is little inconvenient that there is no control over "pre-polling" phase.

I don't know what exactly I want there ;) Maybe something like second (or overall) timeout or websocket disconnect event propagation. At least mentioning this in docs will be useful. Because I was a bit confused why my timeout didn't work until I checked the code and read the docs more carefully.

Of course, if I'm wrong and I missed something, or this question is irrelevant, you can close this issues.

**Comment by DoctorMcKay** [comment]
If I understand you correctly, your confusion came from the fact that the app didn't quit when (from your perspective) no events were outstanding? You'd prefer that the app did exit after you submit an incorrect code and then do nothing?

**Comment by elpaxel** [comment]
Well yes. When you send wrong password it disconnects immediately, but when you input wrong auth code it stays connected. You are right it caused my confusion.
The part about "ClientLogOnResponse" may be not related at all. I just found it strange that after I input wrong auth code, 1 minute passes and Steam sends "ClientLogOnResponse". After that there is disconnect and no reconnection. But I guess that is just how it works.

**Comment by DoctorMcKay** [comment]
Yeah, the reason why it doesn't disconnect is because you could still send the correct code, or confirm the login from your mobile device.

I'm still really not sure why you're observing that ClientLogOnResponse is coming in with no reconnection. It does reconnect the next time it needs to poll the session status, which I confirmed in testing even after sending an incorrect code.
