### ISSUE TITLE
How can I refresh the accessToken via refreshToken? 

### ISSUE THREAD

**Issue by lovesmurf** [DoctorMcKay/node-steam-session#11]
Is it possible to refresh this token via the steam-session package?

**Comment by DoctorMcKay** [comment]
It's not possible yet, but it's on my to-do list.

It's worth mentioning that access tokens are only useful when authenticating as a MobileApp and when using the access token against the WebAPI. Otherwise, access tokens aren't used for anything.

**Comment by lovesmurf** [comment]
> It's not possible yet, but it's on my to-do list.
> 
> It's worth mentioning that access tokens are only useful when authenticating as a MobileApp and when using the access token against the WebAPI. Otherwise, access tokens aren't used for anything.

That is, if you log in through SteamClient token will last 200 days and I also through given me a cookie will be able to send requests during these 200 days?

**Comment by DoctorMcKay** [comment]
Refresh tokens issued via EAuthTokenPlatformType.SteamClient are valid for 200 days. As of yet, nobody has seen any way to refresh those tokens. I suspect that the official client will just make you reauth every 200 days.

You can get new web cookies anytime as long as you have a valid refresh token.

**Comment by lovesmurf** [comment]
> Refresh tokens issued via EAuthTokenPlatformType.SteamClient are valid for 200 days. As of yet, nobody has seen any way to refresh those tokens. I suspect that the official client will just make you reauth every 200 days.
> 
> 
> 
> You can get new web cookies anytime as long as you have a valid refresh token.

How can I get new cookies with a refresh token? Tell me please

**Comment by DoctorMcKay** [comment]
Create a LoginSession object, assign your refresh token to the [refreshToken](https://github.com/DoctorMcKay/node-steam-session#refreshtoken) property, and then call getWebCookies.

```js
let session = new LoginSession(EAuthTokenPlatformType.SteamClient);
session.refreshToken = 'ey...';
let cookies = await session.getWebCookies();
```

**Comment by DoctorMcKay** [comment]
Access tokens can now be refreshed in 1.2.0.

https://github.com/DoctorMcKay/node-steam-session/releases/tag/v1.2.0
