### ISSUE TITLE
Update node-stdlib to last version

### ISSUE THREAD

**Issue by venila** [DoctorMcKay/node-steam-session#19]
You fixed your proxy agent [here](https://github.com/DoctorMcKay/node-stdlib/commit/5959c248bbf43bcfdc18e6c45bf1bf5a85cf61e9), but didn't update this lib to last version of node-stdlib

**Comment by DoctorMcKay** [comment]
It's not worth releasing a new version just to bump dependencies every time a downstream dependency gets a bug fix. The latest version of stdlib is compatible with package.json here, so just run npm update if you need to update.
