### ISSUE TITLE
ERROR: This login attempt has failed! FileNotFound

### ISSUE THREAD

**Issue by WhZzi** [DoctorMcKay/node-steam-session#27]
## Describe the bug
Login occur FileNotExist, result from steamapi

## Versions
1.3.0

## Screenshots and Error Logs
![image](https://github.com/DoctorMcKay/node-steam-session/assets/41277500/fcd2dfd8-6b59-4153-ad63-2f74ea6e9a09)

**Comment by WhZzi** [comment]
Some possible reasons I have discovered so far:

After submitting with a token, it will first send “ https://api.steampowered.com/IAuthenticationService/UpdateAuthSessionWithSteamGuardCode/v1 ”request, as made in your code, but followed by “ https://api.steampowered.com/IAuthenticationService/PollAuthSessionStatus/v1 ” request for has actually returned an Eresult with a successful login, but your code does not seem to recognize the status of this login success (it seems to be because the return value does not carry access_token）

**Comment by DoctorMcKay** [comment]
Yes, this appears to be because Steam is no longer returning access tokens in PollAuthSessionStatus. A simple enough fix.

**Comment by WhZzi** [comment]
> Yes, this appears to be because Steam is no longer returning access tokens in PollAuthSessionStatus. A simple enough fix.

Should we use refresh token to request for access token? becasue it return refresh_token actually

**Comment by DoctorMcKay** [comment]
https://github.com/DoctorMcKay/node-steam-session/releases/tag/v1.3.1

You very likely don't need an access token. If you're using `getWebCookies()` to get your web session, that takes care of everything internally.
