### ISSUE TITLE
There is currently no way to obtain access through post requests_ Did you make a token?

### ISSUE THREAD

**Issue by 4395040** [DoctorMcKay/node-steam-session#28]
There is currently no way to obtain access through post requests_ Did you make a token?

**Comment by 4395040** [comment]
access_token

**Comment by DoctorMcKay** [comment]
Gonna need you to elaborate a little.

**Comment by 4395040** [comment]
What I mean is that there is no way to obtain an accesstoken through a post request now, because before the update https://api.steampowered.com/IAuthenticationService/PollAuthSessionStatus/v1 Can request an accesstoken

**Comment by DoctorMcKay** [comment]
Yes, Steam changed things today.

**Comment by 4395040** [comment]
There's nothing left Thank you

**Comment by DoctorMcKay** [comment]
Ok.
