### ISSUE TITLE
error DuplicateRequest

### ISSUE THREAD

**Issue by Kolosok86** [DoctorMcKay/node-steam-session#3]
if you try to go to steam using totp, there is always a DuplicateRequest error

**Comment by HerrEurobeat** [comment]
Logging in works for me as expected, both with E-Mail and Mobile Steam Guard

**Comment by DoctorMcKay** [comment]
I need to see some code.

**Comment by Kolosok86** [comment]
The problem is gone, i use yesterday "npm i https://github.com/DoctorMcKay/node-steam-session.git" and have errors.
Today i solved this with npm i steam-session
