### ISSUE TITLE
protobuf decode incorrect on "CAuthentication_BeginAuthSessionViaCredentials_Response"

### ISSUE THREAD

**Issue by piyanggoon** [DoctorMcKay/node-steam-session#36]
## Describe the bug
on Vercel Serverless decode protobuf "CAuthentication_BeginAuthSessionViaCredentials_Response" incorrect on "steamid" on "steamid" **local** is "xxxxxxxxxxxxxx348" but on **vercel** is "xxxxxxxxxxxxxx340".

result after calling "sendRequest" on "startSessionWithCredentials" is "eresult": 29 (DuplicateRequest)

## Versions
Vercel Serverless: v18.x
Local: v18.18.2

## Screenshots and Error Logs
If applicable, add screenshots and error logs to help explain your problem.

**Comment by DoctorMcKay** [comment]
You should contact your third-party service provider for issues that are specific to their service.
