### ISSUE TITLE
Steam now has different steamSecureLogin for its 6 domains

### ISSUE THREAD

**Issue by Markovnin** [DoctorMcKay/node-steam-session#38]
## Only one pair of web cookies is returns in getWebCookies
https://github.com/DoctorMcKay/node-steam-session/blob/master/src/LoginSession.ts#L796
Starting yesterday Steam uses different steamLoginSecure cookie for its different domains (steamcommunity, store, help, checkout, etc.) while getWebCookies returns only one. Thus, it cannot be used for requests to steam store, help and other domains.

**Comment by lastelok** [comment]
7 hours ago, in 1.7.2 arleady updated

**Comment by DoctorMcKay** [comment]
npm update
