### ISSUE TITLE
how to use BeginAuthSessionViaCredentials api

### ISSUE THREAD

**Issue by gromaxbro** [DoctorMcKay/node-steam-session#42]
https://api.steampowered.com/IAuthenticationService/BeginAuthSessionViaCredentials/v1/

account_name |   | string | Yes |  
encrypted_password |   | string | Yes | password, RSA encrypted client side
encryption_timestamp |   | uint64 | Yes | timestamp to map to a key - STime
remember_login |   | bool | Yes | deprecated
platform_type |   | {enum} | Yes |  
persistence |   | {enum} | No | whether we are requesting a persistent or an ephemeral session
website_id |   | string | No | (EMachineAuthWebDomain) identifier of client requesting auth
device_details |   | {message} | Yes | User-supplied details about the device attempting to sign in
guard_data |   | string | Yes | steam guard data for client login
language |   | uint32 | Yes |  

like i know  encrypted pass and timstamp 
my question is what to add in gaurd data and language?
i have used rsa to encrypt the password

```

public_key = rsa.PublicKey(int(k1, 16), int(k2, 2))
encrypted_pass = b64encode(rsa.encrypt(password.encode("utf-8"), public_key)).decode("utf-8")
``` 
you guys know any docs or somthing

**Comment by gromaxbro** [comment]
![image](https://github.com/DoctorMcKay/node-steam-session/assets/71826822/47237a2e-27e0-43d2-a100-57b3901d1fc0)

**Comment by DoctorMcKay** [comment]
Read the code, I'm not here to do individual coaching.
