### ISSUE TITLE
Issue with startWithCredentials after packaging with pkg

### ISSUE THREAD

**Issue by lastelok** [DoctorMcKay/node-steam-session#49]
## Description:

When running my code directly with node index.js, everything works as expected. The Steam login session functions correctly, and I can authenticate without issues. Additionally, when bundling the code using esbuild and running the output with node app.js, it also works perfectly.

However, after packaging the bundled code with pkg into an executable (app.exe), the login process fails. Specifically, entering the Steam Guard code leads to the error DuplicateRequest (EResult: 29).

On Node.js v18, everything works correctly after packaging with pkg. The issue occurs specifically with Node.js v22. Additionally, using refreshToken to update the session works as expected, but the login process using credentials fails. Please assist in identifying and resolving the problem.

## Versions
Operating System: Windows 10 x64
Node.js Version: v22.11.0
Pkg Version: 6.1.1
Esbuild Version: 0.24.0
Steam-Session Version: 1.9.0

## Code
index.js:

```
import { LoginSession, EAuthTokenPlatformType, EAuthSessionGuardType } from 'steam-session'
import readline from 'node:readline'

main()

async function main() {
    try {
        const rl = readline.createInterface({
            input: process.stdin,
            output: process.stdout,
        })

        const session = new LoginSession(EAuthTokenPlatformType.WebBrowser, {
            userAgent: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36`,
        })
        session.loginTimeout = 30000 // добавляем время на логин

        session.on('authenticated', async () => {
            console.log(`Success login, account: ${session.accountName}`)
        })

        session.on('timeout', () => {
            console.log(`Failed to login in 30 seconds`)
        })

        session.on('error', (e) => {
            console.log(`Unexpected error. Login failed!`, e)
        })

        const steamGuardCode = await new Promise((resolve) => rl.question('Steam Guard Code? ', resolve))

        const startSessionResult = await session.startWithCredentials({
            accountName: `yourSteamAcc`,
            password: `yourSteamPass`,
            steamGuardCode,
        })

        if (startSessionResult.actionRequired) {
            let reason = ``
            if (Array.isArray(startSessionResult.validActions) && startSessionResult.validActions[0]?.type) {
                reason = EAuthSessionGuardType[startSessionResult.validActions[0]?.type]
            }

            console.log(`On login asked action! ${reason}`)
        }
    } catch (e) {
        console.log(e)
    }
}
```

package.json:
```
{
    "type": "module",
    "dependencies": {
        "@yao-pkg/pkg": "^6.1.1",
        "esbuild": "^0.24.0",
        "steam-session": "^1.9.0"
    }
}
```

## Steps to Reproduce:

1. Take my index.js and package.json and install dependencies.
2. Run the code with `node index.js`:
   - Works as expected.
3. Bundle the code with `esbuild`:
   ```bash
   esbuild index.js --bundle --platform=node --target=node22 --outfile=app.js
 4. Run the code with `node app.js`:
    - Works as expected.
 5. Package the bundled app using pkg
`   bash pkg app.js --targets node22-win-x64 -o app.exe`
 6. Run app.exe
   - Enter the Steam Guard code when prompted.
   - The authentication process fails with the error:

```
Error: DuplicateRequest
    at eresultError (C:\snapshot\repeatBug\app.js)
    at AuthenticationClient.sendRequest (C:\snapshot\repeatBug\app.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AuthenticationClient.submitSteamGuardCode (C:\snapshot\repeatBug\app.js)
    at async LoginSession2.submitSteamGuardCode (C:\snapshot\repeatBug\app.js)
    at async LoginSession2._attemptTotpCodeAuth (C:\snapshot\repeatBug\app.js)
    at async LoginSession2._processStartSessionResponse (C:\snapshot\repeatBug\app.js)
    at async LoginSession2.startWithCredentials (C:\snapshot\repeatBug\app.js)
    at async main (C:\snapshot\repeatBug\app.js) {
  eresult: 29
}
```

## Expected Behavior:
After packaging with pkg, the login session should function identically to how it works when run directly with node index.js or the bundled esbuild output (node app.js).

## Actual Behavior:
The executable built with pkg fails during the login process, resulting in the DuplicateRequest error when submitting the Steam Guard code.

## Logs:

Here are the outputs from each step:

- **Node.js (direct):**
Steam Guard Code? XYP44
Success login, account: 055vvsln

- **Node.js (esbuild):**
Steam Guard Code? XYP44
Success login, account: 055vvsln

- **Pkg (after packaging):**
Steam Guard Code? RR8DR
(node:32196) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Error: DuplicateRequest
    at eresultError (C:\snapshot\repeatBug\app.js)
    at AuthenticationClient.sendRequest (C:\snapshot\repeatBug\app.js)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async AuthenticationClient.submitSteamGuardCode (C:\snapshot\repeatBug\app.js)
    at async LoginSession2.submitSteamGuardCode (C:\snapshot\repeatBug\app.js)
    at async LoginSession2._attemptTotpCodeAuth (C:\snapshot\repeatBug\app.js)
    at async LoginSession2._processStartSessionResponse (C:\snapshot\repeatBug\app.js)
    at async LoginSession2.startWithCredentials (C:\snapshot\repeatBug\app.js)
    at async main (C:\snapshot\repeatBug\app.js) {
  eresult: 29
}

**Comment by Sadzurami** [comment]
Problem caused by `esbuild`.

Module `bytebuffer` bundles wrong and `pkg` missed `memcpy` after that (it will see if use pkg's debug).

Without using esbuild (with commonjs) it's works without any problem.

I guess, it can be solved at esbuild level, but i can't solve it with `--external` flags.

**Comment by lastelok** [comment]
Closing, cause not related to `node-steam-session`
