### ISSUE TITLE
[WebBrowser] - new_guard_data empty in PollAuthSessionStatus

### ISSUE THREAD

**Issue by akuma0** [DoctorMcKay/node-steam-session#8]
Hi!
When i log-in, in PollAuthSessionStatus result, i got access_token & refresh_token but no new_guard_data. 
That's normal ? new_guard_data is maybe available only in SteamClient platform login ? If yes, do you plan a mechanic to refresh login when the steamLoginSecure expire ?

Thank you in advance for your answer!

**Comment by DoctorMcKay** [comment]
new_guard_data is only relevant for the SteamClient platform type, correct.

Getting a Steam Guard token for the WebBrowser platform type is only possible when logging out, which isn't presently implemented.

**Comment by akuma0** [comment]
Ho, ok!
I will look for a way to refresh the steamLoginSecure token automatically because he expires approximately about 24 hours.

**Comment by DoctorMcKay** [comment]
You can call getWebCookies() multiple times. Calling it when your login token expires would be a good way to refresh it.

If you don't still have your original LoginSession object but you do have a refresh token, you can create a new LoginSession, assign your refresh token to the refreshToken property, then call getWebCookies().

Example:

```js
import {LoginSession, EAuthTokenPlatformType} from 'steam-session';

let session = new LoginSession(EAuthTokenPlatformType.WebBrowser);
session.refreshToken = 'token';
let cookies = await session.getWebCookies();
```

**Comment by akuma0** [comment]
That's was i've done yesterday, it's works.
Calling jwt/finalizelogin with refreshToken + steamId
Then call all transfer_info to get the steamLoginSecure (same process than classic login)

Thank you !
