### ISSUE TITLE
Listener is not active

### ISSUE THREAD

**Issue by xxcc520** [DoctorMcKay/node-steam-session#9]
c:\Program Files\nodejs\node_modules\steam-session\dist\helpers.js:17
    let err = new Error(errorMessage || resultMsg);
              ^

Error: RateLimitExceeded

**Comment by DoctorMcKay** [comment]
You exceeded the rate limit

**Comment by xxcc520** [comment]
Why can't the Error event be intercepted, but crash the program directly?

**Comment by DoctorMcKay** [comment]
It can be. That Error comes from the promise returned by `startWithCredentials` being rejected.
